src/retrieve_09S2p000001tD76EAE/objects/Service__c.object
<CustomObject>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pcs</fullName>
                </value>
                <value>
                    <fullName>Hours</fullName>
                </value>
                <value>
                    <fullName>Days</fullName>
                </value>
                <value>
                    <fullName>Months</fullName>
                </value>
                <value>
                    <fullName>Km</fullName>
                </value>
                <value>
                    <fullName>Km2</fullName>
                </value>
                <value>
                    <fullName>Kg</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>SER-{00000}</displayFormat>
        <label>Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DynamicRowItemController.cls
public with sharing class DynamicRowItemController {
    
    @AuraEnabled        
    public static List <String> getUnits() {        
        List <String> allOpts = new list <String> ();        
        Schema.sObjectType objType = Service__c.getSObjectType();        
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();        
        map <String, Schema.SObjectField> fieldMap = objDescribe.fields.getMap();        
        List <Schema.PicklistEntry> values =
            fieldMap.get('Unit__c').getDescribe().getPickListValues();        
        for (Schema.PicklistEntry a: values) {
            allOpts.add(a.getValue());
        }      
        allOpts.sort();
        return allOpts;
    }
}