src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>NIP__c</fullName>
        <label>NIP</label>
        <length>13</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount_in_words__c</fullName>
        <label>Amount in words</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <label>Delivery Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <formula>Issue_Date__c + Payment_Terms__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gross_Total__c</fullName>
        <label>Gross Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Issue_Date__c</fullName>
        <label>Issue Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Issue_Place__c</fullName>
        <label>Issue Place</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Net_Total__c</fullName>
        <label>Net Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Transfer</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>BLIK</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>DotPay</fullName>
                </value>
                <value>
                    <fullName>PayPal</fullName>
                </value>
                <value>
                    <fullName>PayU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Seller__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Seller</label>
        <referenceTo>Seller__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Unpaid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VAT_Total__c</fullName>
        <label>VAT Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Seller__c.object
<CustomObject>
    <fields>
        <fullName>Apt_No__c</fullName>
        <label>Apt. No</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_Account_Number__c</fullName>
        <label>Bank Account Number</label>
        <length>26</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NIP__c</fullName>
        <label>NIP</label>
        <length>13</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_No__c</fullName>
        <label>Street No</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Seller</label>
    <nameField>
        <displayFormat>SEL-{00000}</displayFormat>
        <label>Seller Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sellers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/retrieve_09S2p000001tD76EAE/objects/Service__c.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Gross_Amount__c</fullName>
        <formula>Net_Amount__c + VAT_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gross Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Name_of_Service__c</fullName>
        <label>Name of Service</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Net_Amount__c</fullName>
        <formula>(Net_Price__c-(Net_Price__c* Discount__c))  * Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Price__c</fullName>
        <label>Net Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price_after_discount__c</fullName>
        <formula>Net_Price__c-(Net_Price__c *  Discount__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Price after discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pcs</fullName>
                </value>
                <value>
                    <fullName>Hours</fullName>
                </value>
                <value>
                    <fullName>Days</fullName>
                </value>
                <value>
                    <fullName>Months</fullName>
                </value>
                <value>
                    <fullName>Km</fullName>
                </value>
                <value>
                    <fullName>Km2</fullName>
                </value>
                <value>
                    <fullName>Kg</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VAT_Amount__c</fullName>
        <formula>Net_Amount__c * VAT__r.Value__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VAT Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>VAT__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>VAT</label>
        <referenceTo>VAT__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>SER-{00000}</displayFormat>
        <label>Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/retrieve_09S2p000001tD76EAE/objects/VAT__c.object
<CustomObject>
    <label>VAT</label>
    <nameField>
        <label>VAT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VATs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InvoiceController.cls
/**
 * Created by ociszek001 on 08.05.2019.
 */

public with sharing class InvoiceController {
    public Invoice__c inv { get; set; }
    public String logoURL { get; set;}

    public InvoiceController() {
        inv = getInvoice();
        logoURL = getLogos(inv.Seller__c);
    }

    public String getLogos(Id sellerId) {
        //sprawdz czy sellerId nie jest puste i obsłuzyć
       List<ContentDocumentLink> logoIds= [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = 'a012p00001DcpV5AAJ'];
        if(!logoIds.isEmpty()) {
            String env = URL.getSalesforceBaseUrl().toExternalForm();
            return env + '/sfc/servlet.shepherd/document/download/' + logoIds.get(0).ContentDocumentId;
        }

        return null;
        }


    public Invoice__c getInvoice() {
        //sprawdzic czy result nie jest puste i obsłuzyć. jesili puste stworzyc nowy obiekt        String result = pag;
        inv = [
                SELECT Delivery_Date__c, Issue_Date__c, Issue_Place__c, Name, Seller__r.Company_Name__c,Account__r.NIP__c,Account__r.BillingStreet,Account__r.BillingCity,Account__r.BillingPostalCode,
                        Account__r.Name, Seller__r.NIP__c, Seller__r.Bank_Account_Number__c, Gross_Total__c,
                        Net_Total__c, VAT_Total__c, Amount_in_words__c, Seller__r.Street__c, Seller__r.Street_No__c, Seller__r.Postal_Code__c,
                        Seller__r.City__c, Seller__r.Apt_No__c, Payment__c, Payment_Terms__c, Due_Date__c,Status__c, (SELECT Name_of_Service__c, Price_after_discount__c, Quantity__c, Unit__c, Net_Price__c, Discount__c, Net_Amount__c, VAT__r.Name, VAT_Amount__C, Gross_Amount__c FROM Services__r)
                FROM Invoice__c
                WHERE Id = 'a042p00000vDBK0AAO'
        ];
        return inv;
    }
}