src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>NIP__c</fullName>
        <label>NIP</label>
        <length>13</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <label>Delivery Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Issue_Date__c</fullName>
        <label>Issue Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Issue_Place__c</fullName>
        <label>Issue Place</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Transfer</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>BLIK</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>DotPay</fullName>
                </value>
                <value>
                    <fullName>PayPal</fullName>
                </value>
                <value>
                    <fullName>PayU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Seller__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Seller</label>
        <referenceTo>Seller__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Unpaid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Seller__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Account_Number__c</fullName>
        <label>Bank Account Number</label>
        <length>26</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NIP__c</fullName>
        <label>NIP</label>
        <length>13</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_No__c</fullName>
        <label>Street No</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Seller</label>
    <nameField>
        <displayFormat>SEL-{00000}</displayFormat>
        <label>Seller Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sellers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/retrieve_09S2p000001tD76EAE/objects/Service__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Name_of_Service__c</fullName>
        <label>Name of Service</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Net_Price__c</fullName>
        <label>Net Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pcs</fullName>
                </value>
                <value>
                    <fullName>Hours</fullName>
                </value>
                <value>
                    <fullName>Days</fullName>
                </value>
                <value>
                    <fullName>Months</fullName>
                </value>
                <value>
                    <fullName>Km</fullName>
                </value>
                <value>
                    <fullName>Km2</fullName>
                </value>
                <value>
                    <fullName>Kg</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VAT__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>VAT</label>
        <referenceTo>VAT__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>SER-{00000}</displayFormat>
        <label>Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/retrieve_09S2p000001tD76EAE/objects/VAT__c.object
<CustomObject>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>VAT</label>
    <nameField>
        <label>VAT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VATs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataClass.cls
/**
* Created by ociszek001 on 21.05.2019.
*/
@isTest
public with sharing class TestDataClass {
    public static final String userName = 'devkama23052019@test.com';
    public static final String userAdminName = 'devkon242365432547@test.com';
    public static final String fakeInvoiceNumber = 'FV/2019/01/01';
    public static final String hoursUnit = 'Hours';
    
    public static List<Invoice__c> loadInvoices() {
        List<Account> acc = insertAccount();
        List<Seller__c> sell = insertSeller();
        List<Invoice__c> inv = new List<Invoice__c> {new Invoice__c(Issue_Place__c = 'Warszawa', Delivery_Date__c = Date.newInstance(2019, 06, 13), Seller__c = sell.get(0).Id, Issue_Date__c = Date.newInstance(2019, 06, 13), 
                                                                    Account__c = acc.get(0).Id,Payment_Terms__c = 7, Status__c = 'Unpaid', Payment__c = 'Transfer', Invoice_Number__c =fakeInvoiceNumber)};
                                                                        insert inv;
        return inv;
    }
    
    public static List <Service__c> insertServices(List<VAT__c> vats, List<Invoice__c> invoices) {
        List<Service__c> services = new List <Service__c>();
        for (Invoice__c ic : invoices) {
            for (Integer i = 1; i < 3; i++) {
                Service__c ser = new Service__c(Name_of_service__c = 'Usługa', Net_Price__c = 100 * i, Unit__c = 'Pcs',
                                                Quantity__c = 1 * i, VAT__c = vats.get(0).Id, Invoice__c = ic.Id);
                services.add(ser);
            }
        }
        insert services;
        return services;
    }
    
    public static VAT__c insertVat() {
        VAT__c vat = new VAT__c(Name = '23%', Value__c = 0.23);
        insert vat;
        return vat;
    }
    
    public static ContentDocumentLink insertContent(List<Account> acc) {        
        ContentVersion contentVersion = new ContentVersion(
            Title = 'Test',
            PathOnClient = 'Test.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersion;
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = acc.get(0).Id;
        cdl.ContentDocumentId = documents.get(0).Id;
        cdl.shareType = 'V';
        insert cdl;
        return cdl;
    }
    
    public static List<User> insertUser() {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'OCInvoice User'];       
        List<User> u = new List<User>{new User (Alias = 'newUser', Email = 'newuser@testorg.com',
                                                EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'pl',
                                                LocaleSidKey = 'pl_PL', ProfileId = p.Id,
                                                TimeZoneSidKey = 'Europe/Prague', UserName = userName)};                                                    
                                                    insert u;
        return u;
    }
    
    public static List <User> insertAdmin(){
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        List<User> uAdmin = new List<User>{new User(Alias = 'newAdmin', Email = 'newuserAdmin@testorg.com',
                                                    EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'pl',
                                                    LocaleSidKey = 'pl_PL', ProfileId = p.Id,
                                                    TimeZoneSidKey = 'Europe/Prague', UserName = userAdminName)};
                                                        insert uAdmin;
        return uAdmin;
    }
    
    public static ContentVersion insertContentVersion(){
        ContentVersion contentVersion = new ContentVersion(
            Title = 'Test',
            PathOnClient = 'Test.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        return contentVersion;
    }
    
    public static List<Account> insertAccount(){
        List<Account> acc = new List <Account> {new Account(Name = 'TestTest1', NIP__c = '111-111-11-11', Phone = '123', BillingPostalCode = '12-542', Email__c = 'olga.ciszek@pwc.com')};
            insert acc;
        return acc;
    }
    
    public static List<Seller__c> insertSeller(){
        List<Seller__c> sell = new List<Seller__c> {new Seller__c(Company_Name__c = 'TestCompany', First_Name__c = 'Jan', Last_Name__c = 'Kowalski', NIP__c = '111-112-12-12', Street__c ='Testowa', Street_no__c = '1', City__c = 'Testowo', Postal_Code__c = '00-001', Bank_Account_Number__c = '11111111111111111111111111', Phone__c = '12345' )};
            insert sell;
        return sell;
    }
}