src/objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/retrieve_09S2p000001tD76EAE/objects/Service__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Name_of_Service__c</fullName>
        <label>Name of Service</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Net_Price__c</fullName>
        <label>Net Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pcs</fullName>
                </value>
                <value>
                    <fullName>Hours</fullName>
                </value>
                <value>
                    <fullName>Days</fullName>
                </value>
                <value>
                    <fullName>Months</fullName>
                </value>
                <value>
                    <fullName>Km</fullName>
                </value>
                <value>
                    <fullName>Km2</fullName>
                </value>
                <value>
                    <fullName>Kg</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VAT__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>VAT</label>
        <referenceTo>VAT__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>SER-{00000}</displayFormat>
        <label>Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/retrieve_09S2p000001tD76EAE/objects/VAT__c.object
<CustomObject>
    <label>VAT</label>
    <nameField>
        <label>VAT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VATs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/addDeleteController.cls
public with sharing class addDeleteController {
    
    @AuraEnabled
    public static void saveServices(List<Service__c> ListServices){
        upsert ListServices;
    }
    
    @AuraEnabled
    public static List<Service__c> fetchServices(Id invoiceId){
        List<Service__c> services = new List<Service__c>();
        if(String.isNotBlank(invoiceId)){
            services= [SELECT Name_of_Service__c, Quantity__c,Unit__c,Net_Price__c,VAT__c, Invoice__c from Service__c WHERE Invoice__c =:invoiceId];
        }
        
        if(services.size() == 0){
            Service__c ser = new Service__c(Name_of_Service__c='', Quantity__c=0, Unit__c='Pcs', Net_Price__c=0,VAT__c=null, Invoice__c =invoiceId);
            services.add(ser);
        }
        return services;
    }
    
    @AuraEnabled    
    public static void deleteService(Id serviceId){
        database.delete(serviceId);
    }
}