src/objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Notify_Purchaser__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Notify Purchasers</relationshipLabel>
        <relationshipName>Notify_Purchasers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Notify Purchaser</label>
    <nameField>
        <displayFormat>NP-{000000}</displayFormat>
        <label>Notify Purchaser Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notify Purchasers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestReminderProcessor.cls
@isTest
private class TestReminderProcessor {
    
    @TestSetup
     static void loadData(){       
        List<Invoice__c> inv = new List<Invoice__c>();
        inv = TestDataClass.loadInvoices();
         inv.get(0).Draft__c = false;
         update inv;
    }
    
    @isTest
     static void testReminderProcessor() {        
        Test.startTest();
        ReminderProcessor rp = new ReminderProcessor();
        Id batchId = Database.executeBatch(rp);
        Test.stopTest();
        
        System.assertEquals(1, [select count() from Notify_Purchaser__c]);
    }
}