src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <formula>Issue_Date__c + Payment_Terms__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Seller__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Seller</label>
        <referenceTo>Seller__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Unpaid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Notify_Purchaser__c.object
<CustomObject>
    <fields>
        <fullName>Email_Sent__c</fullName>
        <formula>Invoice__r.Email_Sent__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Notify Purchasers</relationshipLabel>
        <relationshipName>Notify_Purchasers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Seller_Name__c</fullName>
        <label>Seller Name</label>
        <length>180</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Notify Purchaser</label>
    <nameField>
        <displayFormat>NP-{000000}</displayFormat>
        <label>Notify Purchaser Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notify Purchasers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Seller__c.object
<CustomObject>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Seller</label>
    <nameField>
        <displayFormat>SEL-{00000}</displayFormat>
        <label>Seller Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sellers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ReminderProcessor.cls
global class ReminderProcessor  implements Database.Batchable<sObject>, Database.Stateful{
        
    global Database.QueryLocator start (Database.BatchableContext bc){
        return Database.getQueryLocator ('SELECT Id, Draft__c, Due_date__c, Email_Sent__c, Account__r.Email__c, Seller__r.Company_Name__c FROM Invoice__c WHERE Status__c = \'Unpaid\'');
    }
    
    global void execute (Database.BatchableContext bc, List<Invoice__c> scope){
	List<Notify_Purchaser__c> nfList = new List <Notify_Purchaser__c>();		      
        if(scope!=null || !scope.isEmpty()){
            for(Invoice__c inv : scope){
                system.debug(inv.Draft__c==false);
                if((inv.Draft__c==false) && System.today()>inv.Due_date__c){
                    nfList.add(new Notify_Purchaser__c(Invoice__c=inv.Id, Email__c=inv.Account__r.Email__c, Seller_Name__c=inv.Seller__r.Company_Name__c));				                   
                }
            }
        }
        insert nfList;        
    }
    global void finish(Database.BatchableContext bc){       
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, 
            JobItemsProcessed,
            TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob
            WHERE Id = :bc.getJobId()];
        system.debug(job);       
    } 
}