src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Unpaid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/retrieve_09S2p000001tD76EAE/objects/Service__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Name_of_Service__c</fullName>
        <label>Name of Service</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Net_Price__c</fullName>
        <label>Net Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pcs</fullName>
                </value>
                <value>
                    <fullName>Hours</fullName>
                </value>
                <value>
                    <fullName>Days</fullName>
                </value>
                <value>
                    <fullName>Months</fullName>
                </value>
                <value>
                    <fullName>Km</fullName>
                </value>
                <value>
                    <fullName>Km2</fullName>
                </value>
                <value>
                    <fullName>Kg</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VAT__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>VAT</label>
        <referenceTo>VAT__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>SER-{00000}</displayFormat>
        <label>Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/retrieve_09S2p000001tD76EAE/objects/VAT__c.object
<CustomObject>
    <label>VAT</label>
    <nameField>
        <label>VAT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VATs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/retrieve_09S2p000001tD76EAE/classes/TestServiceValidation.cls
/**
 * Created by ociszek001 on 22.05.2019.
 */
@isTest
private class TestServiceValidation {

    @TestSetup
    static void loadData() {
       List<User> u = TestDataClass.insertUser();
        List<Invoice__c> inv = new List<Invoice__c>();
        List<Service__c> ser = new List<Service__c>();
                System.runAs(u.get(0)) {
            Test.startTest();
            VAT__c vat = TestDataClass.insertVat();
            inv = TestDataClass.loadInvoices();
            ser = TestDataClass.insertServices(new List<VAT__c>{
                    vat
            }, inv);
            Test.stopTest();
        }
        System.assertEquals(false, inv.isEmpty());
    }

    @isTest
    static void testUnpaidStatus() {
        List<User> u = [SELECT Id from User WHERE Username = :TestDataClass.userName];
        List <Service__c> ser = new List<Service__c>();
        System.runAs(u.get(0)) {
            ser = [SELECT Net_Price__c FROM Service__c LIMIT 1];
            Test.startTest();
            ser.get(0).Net_Price__c = 3000;
            update ser;
            ser = [SELECT Net_Price__c from Service__c WHERE Id = :ser.get(0).Id];
            Test.stopTest();
        }
        System.assertEquals(false, ser.isEmpty());
        System.assertEquals(3000, ser.get(0).Net_Price__c);
    }

    @isTest
    static void testPaidStatusUpdate() {
        List<User> u = [SELECT Id from User WHERE UserName = :TestDataClass.userName];
        System.runAs(u.get(0)) {
            Invoice__c invoice = [SELECT Id, Status__c FROM Invoice__c LIMIT 1];
            invoice.Status__c = 'Paid';
            Test.startTest();
            update invoice;
            List<Service__c> ser = [SELECT Invoice__c,Net_Price__c FROM Service__c WHERE Invoice__c = :invoice.Id];
            ser.get(0).Net_Price__c = 3000;
            try {
                ServiceValidation.validateService(ser);
            } catch (OCInvoiceException e) {
                System.assertEquals('Adding/Editing/Deleting service impossible while invoice in "Paid" status', e.getMessage());
            }
            Test.stopTest();
        }
    }
    @isTest
    static void testPaidStatusAdd() {
        List<User> u = [SELECT Id from User WHERE UserName = :TestDataClass.userName];
        System.runAs(u.get(0)) {
            Invoice__c invoice = [SELECT Id, Status__c FROM Invoice__c LIMIT 1];
            invoice.Status__c = 'Paid';
            VAT__c vat = [SELECT Id from VAT__c LIMIT 1];
            Test.startTest();
            update invoice;
            List<Service__c> ser = new List<Service__c>();
            Service__c newSer = new Service__c(Name_of_service__c = 'Usługa', Net_Price__c = 100, Unit__c = 'Pcs', Quantity__c = 1, VAT__c = vat.Id, Invoice__c = invoice.Id);
            ser.add(newSer);
            try {
                ServiceValidation.validateService(ser);
            } catch (OCInvoiceException e) {
                System.assertEquals('Adding/Editing/Deleting service impossible while invoice in "Paid" status', e.getMessage());
            }
            Test.stopTest();
        }
    }

    @isTest
    static void testPaidStatusDelete() {
        List<User> u = [SELECT Id from User WHERE UserName = :TestDataClass.userName];
        System.runAs(u.get(0)) {
            List<Invoice__c> invoice = [SELECT Id, Status__c FROM Invoice__c LIMIT 1];
            invoice.get(0).Status__c = 'Paid';
            Test.startTest();
            update invoice;
            List<Service__c> ser = [SELECT Id, Invoice__c FROM Service__c WHERE Invoice__c = :invoice.get(0).Id];
            ser.remove(0);
            try {
                ServiceValidation.validateService(ser);
            } catch (OCInvoiceException e) {
                System.assertEquals('Adding/Editing/Deleting service impossible while invoice in "Paid" status', e.getMessage());
            }
            Test.stopTest();
        }
    }

    @isTest
    static void testServiceUpdate() {
        List<User> u = [SELECT Id from User WHERE UserName = :TestDataClass.userName];
        List <Service__c> ser = new List <Service__c>();
        System.runAs(u.get(0)) {
            ser = [SELECT Id, Net_Price__c, Invoice__c FROM Service__c LIMIT 1];
            ser.get(0).Net_Price__c = 0;
            Test.startTest();
            update ser;
            ser = [SELECT Id, Net_Price__c FROM Service__c WHERE Id = :ser.get(0).Id];
            Test.stopTest();
        }
        System.assertEquals(0, ser.get(0).Net_Price__c);
    }

    @isTest
    static void testServiceDelete() {
        List<User> u = [SELECT Id from User WHERE UserName = :TestDataClass.userName];
        List<Service__c> ser = new List<Service__c>();
        System.runAs(u.get(0)) {
           ser = [SELECT ID from Service__c];
            Test.startTest();
            delete ser;
            Test.stopTest();
            ser = [SELECT Id, Net_Price__c from Service__c];
        }
        System.assertEquals(true, ser.isEmpty());
    }
}