src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Unpaid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/retrieve_09S2p000001tD76EAE/objects/Service__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>SER-{00000}</displayFormat>
        <label>Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ServiceValidation.cls
/**
 * Created by ociszek001 on 19.05.2019.
 */

public with sharing class ServiceValidation {

    public static void validateService(List<Service__c> ser) {
        Set<Id> invoiceIdList = new Set<Id>();
        for (Service__c s : ser) {
            invoiceIdList.add(s.Invoice__c);
        }
        List<Invoice__c> invoices = [SELECT Id, Status__c FROM Invoice__c WHERE Id = :invoiceIdList];
        if (invoices != null || !invoices.isEmpty()) {
            for (Invoice__C inv : invoices) {
                if ('Paid'.equals(inv.Status__c)) {
                    throw new OCInvoiceException('Adding/Editing/Deleting service impossible while invoice in "Paid" status');
                }
            }
        }
    }
}