src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>VAT_Total__c</fullName>
        <label>VAT Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/retrieve_09S2p000001tD76EAE/objects/Service__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>VAT_Amount__c</fullName>
        <formula>Net_Amount__c * VAT__r.Value__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VAT Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>SER-{00000}</displayFormat>
        <label>Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VATCalculation.cls
//Created by ociszek001 on 06.05.2019.
public with sharing class VATCalculation {

    public static void calculateVAT(List <Service__c> ser, String triggerOperation) {
        Set<Id> invoiceIdList = new Set<Id>();
        for (Service__c s : ser) {
            invoiceIdList.add(s.Invoice__c);
        }
        Map<Id, Decimal> invoiceWithVatMap = new Map<Id, Decimal>();
        if ('AFTER_DELETE'.equals(triggerOperation)) {
            for (Id invoiceId : invoiceIdList) {
                invoiceWithVatMap.put(invoiceId, 0);
            }
        }
        for (AggregateResult ar : [SELECT SUM(VAT_Amount__c) sumAmount, Invoice__c FROM Service__c WHERE Invoice__c = :invoiceIdList GROUP BY Invoice__c]) {
            if (ar.get('Invoice__c') != null && ar.get('sumAmount') != null) {
                invoiceWithVatMap.put((Id) ar.get('Invoice__c'), (Decimal) ar.get('sumAmount'));
            }
        }
        List<Invoice__c> invoices = [SELECT Id, VAT_Total__c from Invoice__c WHERE Id = :invoiceWithVatMap.keySet()];
        if (invoices != null || !invoices.isEmpty()) {
            for (Invoice__c inv : invoices) {
                if (invoiceWithVatMap.containsKey(inv.Id)) {
                    inv.VAT_Total__c = invoiceWithVatMap.get(inv.Id);
                }
            }
            update invoices;
        }
    }
}